version: "3.5"
   
services:
  instsite_dev:
    build: .
    restart: always
    container_name: instsite_dev
    volumes:
      - ".:/instsite"
    ports:
      - "${PORT}:8000"
    environment:
      DEBUG: "True"
    networks:
      - https

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}

