# Generated by Django 4.2.8 on 2024-01-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
            ],
        ),
    ]
