# Generated by Django 4.2.8 on 2024-01-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.AlterField(
            model_name='sciencelibrary',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
