# Generated by Django 4.2.8 on 2024-01-14 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_main_options_alter_sciencelibrary_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('image', models.ImageField(default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
                ('date', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Дата должна быть в формате DD.MM.YYYY', regex='^\\d{2}\\.\\d{2}\\.\\d{4}$')])),
            ],
        ),
    ]
