# Generated by Django 4.2.8 on 2024-01-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_mainslider_options_scientists_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientists',
            name='image',
        ),
    ]
