# Generated by Django 4.2.8 on 2024-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_remove_scientists_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientists',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
