# Generated by Django 4.2.8 on 2024-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_alter_scientists_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientists',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
