# Generated by Django 4.2.8 on 2024-01-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_scientists_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientists',
            name='image',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
