# Generated by Django 4.2.8 on 2024-01-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_alter_scientists_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertopinion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
