# Generated by Django 4.2.8 on 2024-01-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_expertopinion_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовка')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Заголовка')),
                ('anons_text', models.CharField(max_length=150, verbose_name='Анонс')),
                ('anons_text_ru', models.CharField(max_length=150, null=True, verbose_name='Анонс')),
                ('anons_text_en', models.CharField(max_length=150, null=True, verbose_name='Анонс')),
                ('anons_text_kk', models.CharField(max_length=150, null=True, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('full_text_ru', models.TextField(null=True, verbose_name='Статья')),
                ('full_text_en', models.TextField(null=True, verbose_name='Статья')),
                ('full_text_kk', models.TextField(null=True, verbose_name='Статья')),
                ('date', models.CharField(max_length=15, verbose_name='Дата публикации')),
                ('image', models.ImageField(default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
    ]
