# Generated by Django 4.2.8 on 2024-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_foundationstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='description',
            field=models.TextField(verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Достижение'),
        ),
    ]
