# Generated by Django 4.2.8 on 2024-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_alter_news_full_text_alter_news_full_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientistsSovet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('title_job', models.CharField(max_length=200, verbose_name='Должность')),
                ('title_job_ru', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('title_job_en', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('title_job_kk', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('orcid', models.CharField(blank=True, max_length=200, null=True, verbose_name='ORCID')),
                ('orcid_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='ORCID')),
                ('orcid_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='ORCID')),
                ('orcid_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='ORCID')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Ученый совет',
                'verbose_name_plural': 'Ученый совет',
            },
        ),
    ]
