# Generated by Django 4.2.8 on 2024-01-30 05:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_scientistssovet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text_kk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Статья'),
        ),
    ]
